version: '3.8'

services:
  backend:
    build:
      context: ./cardapi_backend/cardapi
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - cardgame-network

  frontend:
    build:
      context: ./cardgame_frontend/cardgame
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - cardgame-network

networks:
  cardgame-network:
    driver: bridge
